/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppuntamentoRouteImport } from './routes/appuntamento'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrenotaRouteImport } from './routes/prenota'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBlocchiRouteImport } from './routes/admin.blocchi'
import { Route as AdminGalleriaRouteImport } from './routes/admin.galleria'
import { Route as AdminImpostazioniRouteImport } from './routes/admin.impostazioni'
import { Route as AdminOrariRouteImport } from './routes/admin.orari'
import { Route as AdminPrenotazioniRouteImport } from './routes/admin.prenotazioni'
import { Route as AdminServiziRouteImport } from './routes/admin.servizi'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppuntamentoRoute = AppuntamentoRouteImport.update({
  id: '/appuntamento',
  path: '/appuntamento',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrenotaRoute = PrenotaRouteImport.update({
  id: '/prenota',
  path: '/prenota',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlocchiRoute = AdminBlocchiRouteImport.update({
  id: '/blocchi',
  path: '/blocchi',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleriaRoute = AdminGalleriaRouteImport.update({
  id: '/galleria',
  path: '/galleria',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImpostazioniRoute = AdminImpostazioniRouteImport.update({
  id: '/impostazioni',
  path: '/impostazioni',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrariRoute = AdminOrariRouteImport.update({
  id: '/orari',
  path: '/orari',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPrenotazioniRoute = AdminPrenotazioniRouteImport.update({
  id: '/prenotazioni',
  path: '/prenotazioni',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServiziRoute = AdminServiziRouteImport.update({
  id: '/servizi',
  path: '/servizi',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/appuntamento': typeof AppuntamentoRoute
  '/login': typeof LoginRoute
  '/prenota': typeof PrenotaRoute
  '/admin/blocchi': typeof AdminBlocchiRoute
  '/admin/galleria': typeof AdminGalleriaRoute
  '/admin/impostazioni': typeof AdminImpostazioniRoute
  '/admin/orari': typeof AdminOrariRoute
  '/admin/prenotazioni': typeof AdminPrenotazioniRoute
  '/admin/servizi': typeof AdminServiziRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appuntamento': typeof AppuntamentoRoute
  '/login': typeof LoginRoute
  '/prenota': typeof PrenotaRoute
  '/admin/blocchi': typeof AdminBlocchiRoute
  '/admin/galleria': typeof AdminGalleriaRoute
  '/admin/impostazioni': typeof AdminImpostazioniRoute
  '/admin/orari': typeof AdminOrariRoute
  '/admin/prenotazioni': typeof AdminPrenotazioniRoute
  '/admin/servizi': typeof AdminServiziRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/appuntamento': typeof AppuntamentoRoute
  '/login': typeof LoginRoute
  '/prenota': typeof PrenotaRoute
  '/admin/blocchi': typeof AdminBlocchiRoute
  '/admin/galleria': typeof AdminGalleriaRoute
  '/admin/impostazioni': typeof AdminImpostazioniRoute
  '/admin/orari': typeof AdminOrariRoute
  '/admin/prenotazioni': typeof AdminPrenotazioniRoute
  '/admin/servizi': typeof AdminServiziRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/appuntamento'
    | '/login'
    | '/prenota'
    | '/admin/blocchi'
    | '/admin/galleria'
    | '/admin/impostazioni'
    | '/admin/orari'
    | '/admin/prenotazioni'
    | '/admin/servizi'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appuntamento'
    | '/login'
    | '/prenota'
    | '/admin/blocchi'
    | '/admin/galleria'
    | '/admin/impostazioni'
    | '/admin/orari'
    | '/admin/prenotazioni'
    | '/admin/servizi'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/appuntamento'
    | '/login'
    | '/prenota'
    | '/admin/blocchi'
    | '/admin/galleria'
    | '/admin/impostazioni'
    | '/admin/orari'
    | '/admin/prenotazioni'
    | '/admin/servizi'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppuntamentoRoute: typeof AppuntamentoRoute
  LoginRoute: typeof LoginRoute
  PrenotaRoute: typeof PrenotaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appuntamento': {
      id: '/appuntamento'
      path: '/appuntamento'
      fullPath: '/appuntamento'
      preLoaderRoute: typeof AppuntamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prenota': {
      id: '/prenota'
      path: '/prenota'
      fullPath: '/prenota'
      preLoaderRoute: typeof PrenotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blocchi': {
      id: '/admin/blocchi'
      path: '/blocchi'
      fullPath: '/admin/blocchi'
      preLoaderRoute: typeof AdminBlocchiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/galleria': {
      id: '/admin/galleria'
      path: '/galleria'
      fullPath: '/admin/galleria'
      preLoaderRoute: typeof AdminGalleriaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/impostazioni': {
      id: '/admin/impostazioni'
      path: '/impostazioni'
      fullPath: '/admin/impostazioni'
      preLoaderRoute: typeof AdminImpostazioniRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orari': {
      id: '/admin/orari'
      path: '/orari'
      fullPath: '/admin/orari'
      preLoaderRoute: typeof AdminOrariRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/prenotazioni': {
      id: '/admin/prenotazioni'
      path: '/prenotazioni'
      fullPath: '/admin/prenotazioni'
      preLoaderRoute: typeof AdminPrenotazioniRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/servizi': {
      id: '/admin/servizi'
      path: '/servizi'
      fullPath: '/admin/servizi'
      preLoaderRoute: typeof AdminServiziRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBlocchiRoute: typeof AdminBlocchiRoute
  AdminGalleriaRoute: typeof AdminGalleriaRoute
  AdminImpostazioniRoute: typeof AdminImpostazioniRoute
  AdminOrariRoute: typeof AdminOrariRoute
  AdminPrenotazioniRoute: typeof AdminPrenotazioniRoute
  AdminServiziRoute: typeof AdminServiziRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlocchiRoute: AdminBlocchiRoute,
  AdminGalleriaRoute: AdminGalleriaRoute,
  AdminImpostazioniRoute: AdminImpostazioniRoute,
  AdminOrariRoute: AdminOrariRoute,
  AdminPrenotazioniRoute: AdminPrenotazioniRoute,
  AdminServiziRoute: AdminServiziRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppuntamentoRoute: AppuntamentoRoute,
  LoginRoute: LoginRoute,
  PrenotaRoute: PrenotaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
